# Generated by Django 6.0.8 on 2026-09-27 16:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='identifiant')),
                ('summary', models.CharField(max_length=280, verbose_name='résumé')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(max_length=180, verbose_name='lieu')),
                ('starts_at', models.DateTimeField(verbose_name='début')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('image', models.ImageField(blank=True, upload_to='events/%Y/%m/', verbose_name='visuel')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
                'permissions': [('publish_event', 'Peut publier un événement')],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Participe'), ('maybe', 'À confirmer'), ('declined', 'Ne participe pas')], default='going', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_c5a858_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_rsvp'),
        ),
    ]
