# Generated by Django 6.0.8 on 2026-09-27 16:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='montant')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='devise')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='référence')),
                ('period', models.CharField(max_length=30, verbose_name='période')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('rejected', 'Refusée')], default='pending', max_length=10)),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_all_contributions', 'Peut consulter toutes les cotisations')],
                'indexes': [models.Index(fields=['member', 'status', '-created_at'], name='finance_con_member__ed38a8_idx')],
            },
        ),
    ]
