# Generated by Django 6.0.8 on 2026-09-27 16:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('secretary', 'Secrétaire'), ('treasurer', 'Trésorier'), ('president', 'Président'), ('admin', 'Administrateur')], default='member', max_length=20, verbose_name='rôle')),
                ('email_verified', models.BooleanField(default=False, verbose_name='adresse vérifiée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='fonction')),
                ('term_start', models.DateField(verbose_name='début du mandat')),
                ('term_end', models.DateField(blank=True, null=True, verbose_name='fin du mandat')),
                ('biography', models.TextField(blank=True, verbose_name='biographie')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True, verbose_name='fiche publique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='executive_position', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membre du bureau exécutif',
                'verbose_name_plural': 'bureau exécutif',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='profiles/%Y/%m/', verbose_name='photo de profil')),
                ('university', models.CharField(blank=True, max_length=180, verbose_name='université')),
                ('faculty', models.CharField(blank=True, max_length=180, verbose_name='faculté')),
                ('study_year', models.CharField(blank=True, max_length=80, verbose_name='promotion')),
                ('hometown', models.CharField(blank=True, max_length=120, verbose_name='territoire ou ville d’origine')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='présentation')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='date d’adhésion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil étudiant',
                'verbose_name_plural': 'profils étudiants',
            },
        ),
    ]
